import "server-only";

/**
 * The data layer's public surface. Nothing outside `lib/db/` constructs a
 * PrismaClient, and nothing outside `lib/db/` writes raw SQL (AGENTS.md §5.2,
 * §6 — the pgvector similarity queries are the carve-out and they live here).
 */

export { prisma } from "./client";
export { checkEmbeddingDimensions, type EmbeddingCheck } from "./embedding";
export {
  findStaffUserById,
  findStaffUserByEmail,
  provisionStaffUser,
} from "./staff";
export {
  findFieldSubmissionForNotice,
  readFieldDigest,
  type FieldBriefCard,
  type FieldSubmissionNotice,
  type FieldDigestPayload,
  type FieldSignalCard,
} from "./field";
export {
  classifyEvidenceItem,
  completeEvidenceExtraction,
  countPendingClassification,
  createEvidenceShell,
  createFieldSubmission,
  deleteEvidenceItem,
  fieldSubmissionCitationKey,
  listFieldSubmissionsByStaffUser,
  findEvidenceItemForEmbedding,
  findEvidenceItemForIngestion,
  listEligibleEvidence,
  listEvidenceFacets,
  listPendingClassification,
  loadEvidenceForGenerationContext,
  loadEvidenceListItems,
  NO_EVIDENCE_FILTERS,
  type ClassifyEvidenceResult,
  type CreateEvidenceShellInput,
  type CreateEvidenceShellResult,
  type CreateFieldSubmissionInput,
  type CreateFieldSubmissionResult,
  type FieldSubmissionSummary,
  type EvidenceFacets,
  type EvidenceFilters,
  type EvidenceKeywordQuery,
  type EvidenceListingPage,
  type EvidenceListItem,
} from "./evidence";
export {
  changeBriefStatus,
  findBriefDetail,
  findBriefForEdit,
  findBriefForExport,
  findBriefForReframe,
  findFlagForResolution,
  isEditableStatus,
  listBriefs,
  persistGeneratedBrief,
  persistReframedVersion,
  resolveHallucinationFlag,
  saveBriefVersion,
  type BriefDetail,
  type BriefFlag,
  type BriefForEdit,
  type BriefForExport,
  type BriefForReframe,
  type BriefListItem,
  type BriefStatusEvent,
  type BriefTransition,
  type ChangeBriefStatusInput,
  type ChangeBriefStatusResult,
  type FlagForResolution,
  type GeneratedFlag,
  type PersistGeneratedBriefInput,
  type PersistReframedVersionInput,
  type PersistReframedVersionResult,
  type ResolveFlagInput,
  type ResolveFlagResult,
  type SaveBriefVersionInput,
  type SaveBriefVersionResult,
} from "./briefs";
export {
  findBriefForTranslation,
  findLatestTranslationForBrief,
  saveTranslation,
  type BriefForTranslation,
  type BriefTranslationMessage,
  type BriefTranslationView,
  type SaveTranslationInput,
} from "./brief-translations";
export {
  createBriefGeneration,
  discardBriefGeneration,
  failBriefGeneration,
  findOwnedBriefGeneration,
  markBriefDrafting,
  recordBriefDraft,
  recordBriefFactCheck,
  type CreateBriefGenerationInput,
} from "./brief-generation";
export {
  countEmbeddedChunksByItem,
  listItemsWithUnembeddedChunks,
  listUnembeddedChunks,
  loadChunksForEmbedding,
  purgeEvidenceItemEmbeddings,
  searchEvidenceChunksByVector,
  writeChunkEmbeddings,
  type ChunkForEmbedding,
  type EvidenceChunkMatch,
  type UnembeddedChunk,
} from "./evidence-vectors";
export {
  findEvidenceMatchCandidates,
  findSignalForMatching,
  recordEvidenceMatchRun,
  replaceSignalEvidenceMatches,
  type EvidenceMatchCandidate,
  type RecordEvidenceMatchRunInput,
  type SignalEvidenceMatchInput,
  type SignalForMatching,
} from "./evidence-matches";
export {
  findSignalBriefPrefill,
  findSignalDetail,
  listSignalBoard,
  loadSignalMatchScores,
  reclassifySignalUrgency,
  signalExists,
  type ReclassifySignalUrgencyResult,
  type SignalBoardCard,
  type SignalBoardPage,
  type SignalBriefPrefill,
  type SignalBriefView,
  type SignalDetail,
  type SignalEvidenceMatchView,
  type SignalMatchRunView,
  type SignalPrefillMatch,
  type SignalReclassificationView,
} from "./signal-board";
export {
  createClassifiedSignal,
  findRecentSignalsForDedup,
  recordRadarRun,
  touchSignalDetectedAt,
  type CreateClassifiedSignalInput,
  type RecordRadarRunInput,
} from "./signals";
export {
  listDigestRecipients,
  readDigestWindow,
  type DigestBrief,
  type DigestRadarSummary,
  type DigestRecipient,
  type DigestSignal,
  type DigestWindowReads,
} from "./digest";
export {
  createStakeholder,
  findStakeholderDetail,
  listSharesForBrief,
  listStakeholderOptions,
  listStakeholders,
  recordBriefShare,
  updateStakeholder,
  type BriefShare,
  type RecordBriefShareInput,
  type RecordBriefShareResult,
  type StakeholderDetail,
  type StakeholderInput,
  type StakeholderListItem,
  type StakeholderOption,
  type StakeholderShare,
  type UpdateStakeholderResult,
} from "./stakeholders";
export {
  findBriefForInfluenceDetection,
  listBriefOptionsForInfluence,
  listBriefsForInfluenceDetection,
  listInfluenceEvents,
  listInfluenceEventsRecordedIn,
  logInfluenceEvent,
  readQuarterlyImpactReport,
  recordDetectedInfluenceEvents,
  recordImpactDetectionRun,
  verifyInfluenceEvent,
  type BriefForInfluenceDetection,
  type BriefOption,
  type DetectedInfluenceCandidate,
  type DigestInfluenceEvent,
  type InfluenceEventView,
  type LogInfluenceEventInput,
  type LogInfluenceEventResult,
  type QuarterlyImpactReport,
  type QuarterlyReportEvent,
  type QuarterlyReportEvidence,
  type RecordDetectedInfluenceResult,
  type RecordImpactDetectionRunInput,
  type VerifyInfluenceEventResult,
} from "./influence";
export {
  recordEmbeddingRun,
  recordIngestionFailure,
  recordIngestionSuccess,
  type EmbeddingStage,
} from "./ingestion-log";
