"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";

import { Button, buttonVariants } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { ResearchGapView } from "@/lib/db";
import { ResearchGapPriority, ResearchGapStatus } from "@/lib/generated/prisma/enums";
import { IMPACT_AREA_LABELS } from "../labels";

import { updateResearchGapAction } from "./actions";

const label = (value: string) => value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());

export function GapList({ gaps, canManage }: { gaps: ResearchGapView[]; canManage: boolean }) {
  const [status, setStatus] = useState("all"); const [priority, setPriority] = useState("all"); const [impact, setImpact] = useState("all"); const [query, setQuery] = useState("");
  const visible = useMemo(() => gaps.filter((gap) => (status === "all" || gap.status === status) && (priority === "all" || gap.priority === priority) && (impact === "all" || gap.impactArea === impact) && `${gap.topic} ${gap.description}`.toLowerCase().includes(query.toLowerCase().trim())), [gaps, status, priority, impact, query]);
  return <section className="bg-card border-line rounded-card flex flex-col gap-4 border p-4 tablet:p-5"><div className="flex flex-col gap-3 laptop:flex-row laptop:items-end"><label className="flex flex-1 flex-col gap-1 text-[12px] font-medium">Search<input value={query} onChange={(event) => setQuery(event.target.value)} className="border-line h-9 rounded-md border bg-card px-3 text-[13px]" placeholder="Topic or context" /></label><Filter label="Status" value={status} setValue={setStatus} values={["all", ...Object.values(ResearchGapStatus)]} /><Filter label="Priority" value={priority} setValue={setPriority} values={["all", ...Object.values(ResearchGapPriority)]} /><Filter label="Impact area" value={impact} setValue={setImpact} values={["all", ...Object.keys(IMPACT_AREA_LABELS)]} /></div><p aria-live="polite" className="text-ink-3 text-[12.5px]">{visible.length} {visible.length === 1 ? "priority" : "priorities"} shown</p><ol className="flex flex-col gap-3">{visible.map((gap) => <GapRow key={gap.id} gap={gap} canManage={canManage} />)}</ol>{visible.length === 0 ? <div className="bg-stone border-line rounded-card border p-6 text-center"><h2 className="text-ink text-[14px] font-semibold">No research gaps match these filters</h2><p className="text-ink-3 mt-1 text-[13px]">Clear a filter or log a gap from a signal where the matcher found no strong evidence.</p></div> : null}</section>;
}

function Filter({ label: name, value, setValue, values }: { label: string; value: string; setValue: (value: string) => void; values: string[] }) { return <label className="flex flex-col gap-1 text-[12px] font-medium">{name}<select value={value} onChange={(event) => setValue(event.target.value)} className="border-line h-9 min-w-32 rounded-md border bg-card px-2 text-[13px]">{values.map((entry) => <option key={entry} value={entry}>{entry === "all" ? "Any" : label(entry)}</option>)}</select></label>; }

function GapRow({ gap, canManage }: { gap: ResearchGapView; canManage: boolean }) {
  const router = useRouter();
  const [notes, setNotes] = useState(gap.resolutionNotes ?? ""); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  const update = (input: { status?: ResearchGapStatus; priority?: ResearchGapPriority }) => startTransition(async () => { const result = await updateResearchGapAction({ id: gap.id, ...input, resolutionNotes: input.status === ResearchGapStatus.resolved ? notes : undefined, resolvedEvidenceItemId: gap.resolvedEvidenceItemId }); setMessage(result.ok ? "Saved." : result.refusal.kind === "invalid" ? (result.refusal.fieldErrors.form?.[0] ?? "Could not save.") : result.refusal.kind === "unauthorised" ? result.refusal.message : "Could not save."); if (result.ok) router.refresh(); });
  return <li id={gap.id} className="border-line rounded-card flex flex-col gap-3 border p-4"><div className="flex flex-col justify-between gap-2 tablet:flex-row"><div><div className="flex flex-wrap gap-2 text-[11px] font-semibold"><span className="bg-stone border-line rounded-full border px-2 py-0.5">{IMPACT_AREA_LABELS[gap.impactArea]}</span><span className="bg-watch-surface border-watch-border text-watch-ink rounded-full border px-2 py-0.5">{label(gap.priority)}</span><span className="bg-surface-tint border-surface-tint-border text-primary-ink rounded-full border px-2 py-0.5">{label(gap.status)}</span></div><h2 className="text-ink mt-2 text-[15px] font-semibold">{gap.topic}</h2><p className="text-ink-3 mt-1 max-w-[75ch] text-[13px] leading-relaxed">{gap.description}</p></div>{gap.signalId ? <Link href={`/signals/${gap.signalId}`} className={buttonVariants({ variant: "outline", size: "sm" })}>View signal</Link> : null}</div><div className="border-line/60 flex flex-col gap-2 border-t pt-3 text-[12px] tablet:flex-row tablet:items-center tablet:justify-between"><span className="text-ink-3">Logged by {gap.loggedByName} · {new Date(gap.createdAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}</span><div className="flex flex-wrap gap-2"><Link href={`/evidence/new?gapId=${gap.id}&impactArea=${gap.impactArea}`} className={buttonVariants({ variant: "outline", size: "sm" })}>Ingest evidence</Link>{canManage ? <><select aria-label={`Priority for ${gap.topic}`} disabled={pending} value={gap.priority} onChange={(event) => update({ priority: event.target.value as ResearchGapPriority })} className="border-line h-8 rounded-md border bg-card px-2 text-[12px]">{Object.values(ResearchGapPriority).map((value) => <option key={value} value={value}>{label(value)}</option>)}</select><select aria-label={`Status for ${gap.topic}`} disabled={pending} value={gap.status} onChange={(event) => update({ status: event.target.value as ResearchGapStatus })} className="border-line h-8 rounded-md border bg-card px-2 text-[12px]">{Object.values(ResearchGapStatus).map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></> : null}</div></div>{canManage && gap.status !== ResearchGapStatus.resolved ? <div className="flex flex-col gap-2 tablet:flex-row"><Textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Resolution notes (required when resolving)" className="min-h-18 text-[13px]" /><Button type="button" variant="outline" size="sm" disabled={pending || notes.trim().length < 3} onClick={() => update({ status: ResearchGapStatus.resolved })}>Mark resolved</Button></div> : null}{message ? <p className="text-watch-ink text-[12px]">{message}</p> : null}</li>;
}
